import './globals.scss'
import { Fira_Code} from "next/font/google";
import SkillGrid from "@/components/skillGrid/skillGrid";

const firaCode = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={firaCode.className}>

      {/*<SkillGrid/>*/}
      <div className="bg-right-fixed"></div>
      {children}
      </body>
    </html>
  )
}
